### PR TITLE
Comment out crypto section from navbar

### LINKED ISSUE #551: Hide the "Crypto" link from Navbar
## Overview
The "Crypto" link is visible on all the sites. It should be hidden from all the sites. Because it is not working as of now.

Parent Ticket: https://github.com/Real-Dev-Squad/todo-action-items/issues/152

### PR DESCRIPTION
**Pull request by 0xatulpatil**
### What is the change?

Hiding the "Crypto" section from the "website-member" navbar.
Fixes #551. 
### Is it bug?

- Steps to repro
- Expected
- Actual

### \*Dev Tested?

- [x] Yes
- [ ] No

#### Platforms

- [ ] Web

#### Browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox

### Before / After Change Screenshots

> For visual or interaction changes. Can be video / screenshot.
image

### CODE REVIEW

**Review by Pratiyushkumar — APPROVED** [review]

File: src/constants/AppConstants.js [hunk 1]
```diff
@@ -35,11 +35,11 @@ const NAVMENU = [
     name: 'Members',
     path: 'https://members.realdevsquad.com/',
   },
-  {
-    id: '5',
-    name: 'Crypto',
-    path: 'https://crypto.realdevsquad.com/',
-  },
+  // {
```
Comment (iamitprakash) [inline src/constants/AppConstants.js:38]: please remove the commented code

**Review by iamitprakash — CHANGES_REQUESTED** [review]

**Review by iamitprakash — APPROVED** [review]
