### PR TITLE
Fix/error in sign in flow

### LINKED ISSUE #316: Fix the login issue in navbar
Issue for the fix
- Issue #261 
- PR #265 
**Bugs Encountered**
- `/users/self` call giving 404
image

### PR DESCRIPTION
**Pull request by Kshashank99**
Closes #316 
### What is the change?

- Setup sign in flow for the user and standardized navbar
- Fixed error in fetching user detail in sign in flow
- Now user can access member site by signing in through github.

### Is it bug?
yes

- Steps to repro
- - signin flow
- Expected
- Actual

### \*Dev Tested?

- [x] Yes
- [ ] No

#### Platforms

- [x] Web

#### Browsers

- [x] Chrome
- [x] Safari
- [ ] Firefox

### Before / After Change Screenshots

> For visual or interaction changes. Can be video / screenshot.
Before: 
image
image

After:
- Without sigin:
image
- signed in:
image
image

### CODE REVIEW

File: src/components/UI/navbar/index.js [hunk 1]
```diff
@@ -47,21 +47,23 @@ const Navbar = () => {
...
         })
         .then((responseJson) => {
-          if (!responseJson.incompleteUserDetails) {
-            setIsLoggedIn(true);
-            setUserData({
-              userName: responseJson.username,
-              firstName: responseJson.first_name,
-              profilePicture: responseJson.picture.url?.DEFAULT_AVATAR,
-            });
+          if (responseJson.incompleteUserDetails) {
```
Comment (harshith-venkatesh) [inline src/components/UI/navbar/index.js:54]: Is it a good idea to go  with `!!responseJson.incompleteUserDetails`?
In the contract we are going ahead with `incompleteUserDetails` as boolean only right?

File: src/components/UI/navbar/index.js [hunk 2]
```diff
@@ -47,21 +47,23 @@ const Navbar = () => {
...
+            window.open('https://my.realdevsquad.com/signup', '_blank');
```
Comment (harshith-venkatesh) [inline src/components/UI/navbar/index.js:55]: Could you look into the importance of `no-referrer` and `no-opener` here please
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener

File: src/components/UI/navbar/index.js [hunk 3]
```diff
@@ -47,21 +47,23 @@ const Navbar = () => {
...
+          setIsLoggedIn(true);
+          setUserData({
+            userName: responseJson.username,
+            firstName: responseJson.first_name,
+            profilePicture: responseJson.picture?.url ?? DEFAULT_AVATAR,
+          });
         })
         .catch((err) => {
-          return err;
+          console.error(err);
```
Comment (harshith-venkatesh) [inline src/components/UI/navbar/index.js:66]: Was it decided to go ahead with `console.error` here?

File: src/styles/global-styles.scss [hunk 4]
```diff
@@ -27,3 +27,7 @@ h2 {
 h3 {
   font-size: 1.33rem;
 }
+
+.d-none {
+  display: none !important;
```
Comment (harshith-venkatesh) [inline src/styles/global-styles.scss:32]: Please look for a way of not using `!important` here
https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Review by harshith-venkatesh — CHANGES_REQUESTED** [review]

**Comment by Kshashank99** [comment]
@rohan09-raj I took the Screenshot a bit early before page could load completely. You can even see in bottom left corner that browser is still processing some request while taking the ss. So everything is fine🙂

File: src/components/UI/navbar/index.js [hunk 5]
```diff
@@ -171,10 +174,10 @@ const Navbar = () => {
             >
               <Link href={LOGIN_URL}>
                 <a
-                  className={`${styles.btnLogin}${isLoggedIn ? 'd-none' : ''}`}
+                  className={`${styles.btnLogin} ${isLoggedIn ? 'd-none' : ''}`}
                 >
                   <button type="button" className={styles.btnLoginText}>
-                    Sign In With GitHub
+                    Sign In With GitHub {isLoggedIn}
```
[the remark this answers is not in the document]
Comment (Kshashank99) [reply src/components/UI/navbar/index.js:180]: No significance ,i was just trying to debug in place of console.log. I'll remove it

File: src/components/UI/navbar/index.js (hunk 1 above)
Comment (Kshashank99) [reply src/components/UI/navbar/index.js:54]: Yes @harshith-venkatesh incompleteUserDetails is a boolean property (see in below ss). Therefore the logic inside if condition will work perfectly. I didn't get , Did  you say `!!responseJson.incompleteUserDetails` in a better option than `responseJson.incompleteUserDetails`. If yes , how? Both checking the same thing right?
image

Comment (harshith-venkatesh) [reply src/components/UI/navbar/index.js:54]: Since it is perfect Boolean i guess we are good here

**Comment by rohan09-raj** [comment]
> @rohan09-raj I took the Screenshot a bit early before page could load completely. You can even see in bottom left corner that browser is still processing some request while taking the ss. So everything is fine🙂. I'll replace the ss.

Ohh okk, yes please replace that

File: src/components/UI/navbar/index.js (hunk 2 above)
Comment (Kshashank99) [reply src/components/UI/navbar/index.js:55]: Yes , noopener makes `window.opener= null`(of new tab) which nullify the reference of parent tab from the new tab opened which helps in securing the parent site.

Comment (harshith-venkatesh) [reply src/components/UI/navbar/index.js:55]: Do we need to pass in some information here?

File: src/styles/global-styles.scss (hunk 4 above)
Comment (Kshashank99) [reply src/styles/global-styles.scss:32]: I removed this css from here(global) and applied in the the navbar.css but it's not working. I wonder why🤔. I tried looking for it's alternative but still no clue yet. Still looking

File: src/components/UI/navbar/index.js (hunk 3 above)
Comment (sumitd94) [reply src/components/UI/navbar/index.js:66]: Let's leave it for now.

File: src/components/UI/navbar/index.js [hunk 6]
```diff
@@ -95,7 +98,7 @@ const Navbar = () => {
             }
           >
             <Link href={LOGIN_URL}>
-              <a className={`${styles.btnLogin}${isLoggedIn ? 'd-none' : ''}`}>
+              <a className={`${styles.btnLogin} ${isLoggedIn ? 'd-none' : ''}`}>
```
Comment (sumitd94) [inline src/components/UI/navbar/index.js:101]: Why not just render this `Link` tag if the user is not logged in? 🤔

File: src/components/UI/navbar/navbar.module.scss [hunk 7]
```diff
@@ -138,6 +138,12 @@
 .homes {
   display: none;
 }
+.navBar li.navBarLoginLi .d-none {
+  display: none;
+}
+.navBar li.navBarLoginLi .d-none {
+  display: none;
+}
```
Comment (harshith-venkatesh) [inline src/components/UI/navbar/navbar.module.scss:146]:
```suggestion
.navBar li.navBarLoginLi .d-none {
  display: none;
}
.navBar li.navBarLoginLi .d-none {
  display: none;
}
```
Do we need this, since we are not adding any class

File: src/styles/global-styles.scss (hunk 4 above)
Comment (harshith-venkatesh) [reply src/styles/global-styles.scss:31]: this one needs to be removed

**Review by harshith-venkatesh — CHANGES_REQUESTED** [review]

File: src/components/UI/navbar/navbar.module.scss (hunk 7 above)
Comment (harshith-venkatesh) [inline src/components/UI/navbar/navbar.module.scss:146]:
```suggestion

```

**Review by harshith-venkatesh — CHANGES_REQUESTED** [review]

File: src/components/UI/navbar/index.js [hunk 8]
```diff
@@ -87,48 +93,48 @@ const Navbar = () => {
...
+                        src={
+                          isLoggedIn
+                            ? `${userData.profilePicture}`
+                            : `${DEFAULT_AVATAR}`
+                        }
+                        alt="Profile pic"
+                      />
+                    </a>
+                  </Link>
+                </div>
```
Comment (harshith-venkatesh) [inline src/components/UI/navbar/index.js:134]: Could we go ahead with ternary operator?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

Comment (harshith-venkatesh) [reply src/components/UI/navbar/index.js:134]: NIT

**Review by sumitd94 — APPROVED** [review]
